### ISSUE TITLE
Create Acceptance Email Body

### ISSUE THREAD

**Issue by juancwu** [LaurierHawkHacks/Dashboard#301]
We use HTML as the email body, so you can create an acceptance email using HTML. I would look into HTML in email.

Make sure you follow the format we have in mailchimp (Account in notion)

**Comment by teoh4770** [comment]
@juancwu 

- Do we use mailchimp to create the acceptance email?
- Just to make sure, I need to access the HawkHacks account to access mailchimp right?
<img width="878" alt="Screenshot 2024-05-04 at 4 43 26 PM" src="https://github.com/LaurierHawkHacks/Dashboard/assets/98545971/13c2b40d-a51b-47b5-a073-a6e35cb49f0d">
